#!/bin/bash
set -xe

apt-get install -y "${APTGETOPT[@]}" clang-8 lld-8 llvm-8-dev

ln -sf /usr/bin/clang-8        /usr/bin/clang
ln -sf /usr/bin/clang++-8      /usr/bin/clang++
ln -sf /usr/bin/clang-cpp-8    /usr/bin/clang-cpp
ln -sf /usr/bin/lld-8          /usr/bin/lld

ln -sf /usr/bin/clang          /usr/bin/cc
ln -sf /usr/bin/clang          /usr/bin/gcc
ln -sf /usr/bin/clang          /usr/bin/x86_64-linux-gnu-gcc
ln -sf /usr/bin/clang++        /usr/bin/c++
ln -sf /usr/bin/clang++        /usr/bin/g++
ln -sf /usr/bin/clang++        /usr/bin/x86_64-linux-gnu-g++
ln -sf /usr/bin/clang-cpp      /usr/bin/cpp
ln -sf /usr/bin/clang-cpp      /usr/bin/x86_64-linux-gnu-cpp

ln -sf /usr/bin/lld            /usr/bin/ld
ln -sf /usr/bin/lld            /usr/bin/x86_64-linux-gnu-ld

ln -sf /usr/bin/llvm-ar-8      /usr/bin/ar
ln -sf /usr/bin/llvm-ranlib-8  /usr/bin/ranlib
ln -sf /usr/bin/llvm-objcopy-8 /usr/bin/objcopy
ln -sf /usr/bin/llvm-objcopy-8 /usr/bin/strip
ln -sf /usr/bin/llvm-nm-8      /usr/bin/nm
ln -sf /usr/bin/llvm-objdump-8 /usr/bin/objdump
ln -sf /usr/bin/llvm-as-8      /usr/bin/as

exit 0
